### ISSUE TITLE
[Bug]: Conflict with Light Overlay's Configuration

### ISSUE THREAD

**Issue by Therrous** [Fuzss/puzzleslib#137]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

21.1.11

### Other Mods Involved (Required)

Yes

### Notes (Required)

While Puzzles Lib is installed, the configs of Light Overlay [https://github.com/shedaniel/LightOverlay](https://github.com/shedaniel/LightOverlay) develop an issue with the sliders. The values are no longer changed by adjusting them, and the sliders themselves can be freely dragged out of their frames towards their corresponding text. This was confirmed in a NeoForge environment with only Puzzles Lib, Light Overlay, and LO's dependencies. 
![image](https://github.com/user-attachments/assets/3550bf99-e26a-4aa9-b082-97cbd295377d)

### latest.log (Required)

https://gist.github.com/Therrous/f717ba6d0dcb317eb3bf46e3c9a838cb

**Comment by Fuzss** [comment]
Yeah, so Puzzles Lib uses an Access Transformer to turn `AbstractSliderButton::setValue(D)V` public. 
The sliders from Light Overlay seem to contain a method with the same descriptor and name, which then accidentially overrides the previously private and inaccessible vanilla method.
I can't remove the access change since I need to override the method in some place.
The easiest solution is for Light Overlay to simply change their method name to anything else.
Please report this to them.
