### ISSUE TITLE
[Bug]: Some of your mods (this included) don't have a version in PrismLauncher 6.3

### ISSUE THREAD

**Issue by rapus95** [Fuzss/puzzleslib#33]
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.19.3

### Mod Version (Required)

v5 I guess?

### Notes (Required)

Air Hop for some reason has one but at the bottom end there are more from you that don't
![image](https://user-images.githubusercontent.com/5960902/228949275-d9091290-675c-4a8f-9199-fc54b14ffbce.png)

**Comment by Fuzss** [comment]
Interesting, thanks!

Seems to be a problem with the `fabric.mod.json` files. The files are all valid, but the ones that do work have been rewritten by Loom (for adding the Cardinal Components nested jar entry).
Loom has removed all empty lines and replaced some chars with the unicode representation, so the issue should be related to that.

But this should really be up to PrismLauncher to solve, since Fabric Loader has no issue reading the `fabric.mod.json` file (and Quilt Loader shouldn't have one, too).

**Comment by rapus95** [comment]
heads up, due to some problems I got to restart prism. most of the mods were just gone. As it seems it indeed was a prism issue. That I cannot even reproduce. So I might finally be able to try out the SpikeySpikes in a oneblock setting mobfarm! Thanks for producing so many nice mods! And hell, you have an extremely fast response time, like that!

**Comment by Fuzss** [comment]
Thanks a lot for the kind words!
