### ISSUE TITLE
[Crash]: Games crashes while loading into the world

### ISSUE THREAD

**Issue by Cape-City** [Fuzss/puzzleslib#39]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.3

### Mod Version (Required)

5.0.24

### Notes (Required)

With the v5.0.19 of the puzzleslib mod loading into the world did not has this issue so far. When updating to one of the last 3 versions (5.0.20, 5.0.22 or 5.0.24), this issue happens in 2 from 10 times while loading into the world.

### Crash Report (Required)

https://gist.github.com/Cape-City/f0300178beac6ff6dfd9522257510074

### latest.log (Optional)

https://gist.github.com/Cape-City/0ba6522b681a3ffff54c7149f3797739

**Comment by Fuzss** [comment]
Thanks for the report! The issue seems unrelated to Puzzles Lib though.

The crash is caused by an infinite loop in the parent-child relationship of advancements when checking their visibility (an advancement seems to be its own parent/child). Probably just one random mod/data pack adding the faulty advancement. Puzzles Lib isn't touching anything related to advancements, so there isn't really a chance it could be the cause.

**Comment by Cape-City** [comment]
Thanx for your reply, but where do you see, that the advancements had something to do with this issue? The only mods i kniw which do something with advancements are:

More Advancements (Fabric) - pardeus1 - moreadvancementsmod-1.2.2-1.19.3.jar
Better Advancements - way2muchnoise - BetterAdvancements-Fabric-1.19.3-0.3.1.151.jar
Pufferfish's Skills - Pufferfish - puffish_skills-0.1.2-1.19.3-fabric.jar

If i disable them, the issue is still there :(

**Comment by Fuzss** [comment]
Great! [Crashy](https://crashy.net/) is also really good for making crash-reports readable btw.
