### ISSUE TITLE
[Crash]: Minecraft 1.20.1 with Fabric Loader 0.14.24

### ISSUE THREAD

**Issue by ImASadBoy** [Fuzss/puzzleslib#83]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

puzzleslib 8.1.7

### Notes (Required)

Server crashes on startup due to following error: https://pastebin.com/z34LDvGW

### Crash Report (Required)

https://pastebin.com/z34LDvGW

### latest.log (Optional)

https://pastebin.com/z34LDvGW

**Comment by Fuzss** [comment]
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectChunksListClone(I)Ljava/util/ArrayList; in lithium.mixins.json:alloc.chunk_ticking.ServerChunkManagerMixin from mod lithium failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.lithium.refmap.json`

Lithium is conflicting with another mod, report it to them.
