### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by some-du6e** [Fuzss/puzzleslib#86]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20,1

### Mod Version (Required)

8.1.8

### Notes (Required)

1. launch
2. crash

### Crash Report (Required)

https://pastebin.com/FSfxjast

**Comment by Fuzss** [comment]
Has nothing to do with Puzzles Lib:
`Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for mixins.essential.json:client.renderer.entity.Mixin_ApplyPoseTransform_Cape from mod essential during activity: [Transform -> Method isolateCapeMatrix(Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;ILnet/minecraft/class_742;FFFFFFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> INVOKEVIRTUAL -> net/minecraft/class_1159::method_22668:()V]
`
