### ISSUE TITLE
[Crash]: Crash on launch

### ISSUE THREAD

**Issue by Hexblood** [Fuzss/puzzleslib#89]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.1.11

### Notes (Required)

Built a personal pack and getting this crash during launch. 

I think I have seen the error in the latest.log in other packs I have made in other MC versions, but no crash.

### Crash Report (Required)

https://pastebin.com/hscza3W3

### latest.log (Optional)

https://pastebin.com/tLRxQNRh

**Comment by Fuzss** [comment]
This is your error, has nothing to do with Puzzles Lib:
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector hideElytra(Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;ILnet/minecraft/class_1309;FFFFFF)Z in terramine.mixins.json:client.render.ElytraLayerMixin from mod terramine failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap terramine-refmap.json`
